adapter: tofu
benchmark_name: tofu_forget10
forget_path: /media/volume/llm/subo/unlearning-project/tofu_benchmark/forget10.json
full_path: /media/volume/llm/subo/unlearning-project/tofu_benchmark/full.json
question_key: question
answer_key: answer
system_prompt: You are a helpful assistant.
selected_output_filename: forget10_selected.jsonl
forget_corpus_filename: forget10-forget-corpus.jsonl
retain_corpus_filename: forget10-retain-corpus.jsonl
open_unlearning:
  train:
    experiment: unlearn/tofu/default
  eval:
    experiment: eval/tofu/default
