adapter: wmdp
benchmark_name: wmdp_bio
forget_path: /media/volume/llm/subo-fun/unlearning-data-improvement/data/wmdp_bio_filtered.json
full_path: /media/volume/llm/subo-fun/unlearning-data-improvement/data/wmdp_bio.json
data_split: bio
question_key: question
answer_key: answer
choices_key: choices
include_choices: true
system_prompt: You are a helpful assistant.
selected_output_filename: forget_selected.jsonl
forget_corpus_filename: bio-forget-corpus.jsonl
retain_corpus_filename: bio-retain-corpus.jsonl
open_unlearning:
  train:
    experiment: unlearn/wmdp/default
  eval:
    experiment: eval/wmdp/default
